# Generated by Django 4.1.3 on 2022-11-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="envio",
            new_name="pagos",
        ),
    ]
