# Generated by Django 4.1.3 on 2022-11-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_rename_envio_pagos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagos",
            old_name="numeroFAC",
            new_name="numero_factura",
        ),
    ]
