# Generated by Django 4.1.3 on 2022-11-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_alter_facturacion_cuit_cliente_and_more"),
        ("pagos", "0003_rename_numerofac_pagos_numero_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="numero_factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facpagos",
                to="facturacion.facturacion",
                verbose_name="Nª de Factura",
            ),
        ),
    ]
