# Generated by Django 4.1.3 on 2022-11-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturacion", "0001_initial"),
        ("ordencompra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="envio",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fechaenvio", models.DateField()),
                ("fecharecepcion", models.DateField(blank=True)),
                ("emailenviado", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "numeroFac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facenvios",
                        to="facturacion.facturacion",
                    ),
                ),
                (
                    "numeroOC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordencompra.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "envio",
                "verbose_name_plural": "envios",
            },
        ),
    ]
