# Generated by Django 4.1.3 on 2022-11-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("envios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="envio",
            old_name="emailenviado",
            new_name="Email_enviado",
        ),
        migrations.RenameField(
            model_name="envio",
            old_name="fechaenvio",
            new_name="Fecha_envio",
        ),
        migrations.RenameField(
            model_name="envio",
            old_name="fecharecepcion",
            new_name="Fecha_recepcion",
        ),
        migrations.RenameField(
            model_name="envio",
            old_name="numeroFac",
            new_name="Numero_Factura",
        ),
        migrations.RenameField(
            model_name="envio",
            old_name="numeroOC",
            new_name="Numero_OC",
        ),
    ]
