# Generated by Django 4.1.3 on 2022-11-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_alter_facturacion_cuit_cliente_and_more"),
        ("ordencompra", "0004_alter_ordencompra_cuit_cliente_and_more"),
        ("envios", "0002_rename_emailenviado_envio_email_enviado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envio",
            name="Email_enviado",
            field=models.EmailField(max_length=254, verbose_name="Email Enviado"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="Fecha_envio",
            field=models.DateField(verbose_name="Fecha de Envio"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="Fecha_recepcion",
            field=models.DateField(blank=True, verbose_name="Fecha de Recepcion"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="Numero_Factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facenvios",
                to="facturacion.facturacion",
                verbose_name="Nº de Factura",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="Numero_OC",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ordencompra.ordencompra",
                verbose_name="Nº de Orden de Compra",
            ),
        ),
    ]
