# Generated by Django 4.1.3 on 2022-11-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cliente",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("cuit", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
            },
        ),
    ]
