# Generated by Django 4.1.3 on 2022-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.IntegerField(blank=True),
        ),
    ]
