# Generated by Django 4.1.3 on 2022-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_cliente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
