# Generated by Django 4.1.3 on 2022-11-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("ordencompra", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="facturacion",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("numeroFAC", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
                ("importe", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "cuit_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "cuit_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "numeroOC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordencompra.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura",
                "verbose_name_plural": "facturas",
            },
        ),
    ]
