# Generated by Django 4.1.3 on 2022-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturacion",
            name="descripcion",
            field=models.TextField(max_length=300),
        ),
    ]
