# Generated by Django 4.1.3 on 2022-11-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_alter_facturacion_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facturacion",
            old_name="numeroFAC",
            new_name="numero_factura",
        ),
        migrations.RenameField(
            model_name="facturacion",
            old_name="numeroOC",
            new_name="numero_oc",
        ),
    ]
