# Generated by Django 4.1.3 on 2022-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="direccion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.IntegerField(blank=True),
        ),
    ]
