# Generated by Django 4.1.3 on 2022-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_alter_empresa_direccion_alter_empresa_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="direccion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
