# Generated by Django 4.1.3 on 2022-11-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordencompra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordencompra",
            name="descripcion",
            field=models.TextField(max_length=300),
        ),
    ]
