# Generated by Django 4.1.3 on 2022-11-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordencompra", "0002_alter_ordencompra_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordencompra",
            old_name="fechafin",
            new_name="fecha_fin",
        ),
        migrations.RenameField(
            model_name="ordencompra",
            old_name="fechainicio",
            new_name="fecha_inicio",
        ),
        migrations.RenameField(
            model_name="ordencompra",
            old_name="numeroOC",
            new_name="numero_oc",
        ),
    ]
